In [2]:
import pandas as pd
import os
import seaborn as sns

In [6]:
os.chdir('c:\\Users\\Pablo\\Documents\\Climate DataThon 2022\\Climate-DataThon-2022\\Ocean Watch Data')

# Notes

Seems like for many countries the data was by decade for a while
We are going to need to filter some of these countries out possibly

In [8]:
marine_protection = pd.read_csv('Data\ocn_023_rw1_marine_protection_edit.csv')
marine_protection['datetime'] = pd.to_datetime(marine_protection['datetime'] )
marine_protection

,the_geom,cartodb_id,iso,country,designation,domain,measure,calculation_method,scope,year,unit_code,unit,value,datetime
0,NaN,1795,BRA,Brazil,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2018,PC,Percentage,26.650084,2018-01-01
1,NaN,4177,SAU,Saudi Arabia,"All, including data recorded as points",Marine,Square kilometers,Total for category,Country,1950,KM2,Square kilometres,6.570000,1950-01-01
2,NaN,5448,G20,G20,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2017,PC,Percentage,10.232679,2017-01-01
3,NaN,6536,URY,Uruguay,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2003,PC,Percentage,0.000717,2003-01-01
4,NaN,1,AUS,Australia,"All, including data recorded as points",Marine,Square kilometers,Total for category,Country,1950,KM2,Square kilometres,153.990000,1950-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6637,NaN,6637,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2017,PC,Percentage,9.851974,2017-01-01
6638,NaN,6638,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2018,PC,Percentage,10.907854,2018-01-01
6639,NaN,6639,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2019,PC,Percentage,11.002787,2019-01-01
6640,NaN,6640,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2020,PC,Percentage,11.002787,2020-01-01
6641,NaN,6641,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2021,PC,Percentage,11.002787,2021-01-01

### Get just the percentage, I imagine that's what we'd want

In [9]:
marine_protection_percent = marine_protection[marine_protection['unit_code'] == 'PC']
marine_protection_percent

,the_geom,cartodb_id,iso,country,designation,domain,measure,calculation_method,scope,year,unit_code,unit,value,datetime
0,NaN,1795,BRA,Brazil,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2018,PC,Percentage,26.650084,2018-01-01
2,NaN,5448,G20,G20,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2017,PC,Percentage,10.232679,2017-01-01
3,NaN,6536,URY,Uruguay,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2003,PC,Percentage,0.000717,2003-01-01
33,NaN,30,AUS,Australia,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,1950,PC,Percentage,0.002079,1950-01-01
34,NaN,31,AUS,Australia,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,1960,PC,Percentage,0.002081,1960-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6637,NaN,6637,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2017,PC,Percentage,9.851974,2017-01-01
6638,NaN,6638,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2018,PC,Percentage,10.907854,2018-01-01
6639,NaN,6639,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2019,PC,Percentage,11.002787,2019-01-01
6640,NaN,6640,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2020,PC,Percentage,11.002787,2020-01-01
6641,NaN,6641,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2021,PC,Percentage,11.002787,2021-01-01

In [10]:
marine_protection_percent[marine_protection_percent['country'] == 'United States']

,the_geom,cartodb_id,iso,country,designation,domain,measure,calculation_method,scope,year,unit_code,unit,value,datetime
1310,NaN,1306,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,1950,PC,Percentage,0.278535,1950-01-01
1311,NaN,1307,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,1960,PC,Percentage,0.307124,1960-01-01
1312,NaN,1308,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,1970,PC,Percentage,0.383726,1970-01-01
1313,NaN,1309,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,1980,PC,Percentage,0.716241,1980-01-01
1314,NaN,1310,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,1985,PC,Percentage,0.853605,1985-01-01
1315,NaN,1311,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,1990,PC,Percentage,1.024347,1990-01-01
1316,NaN,1312,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,1995,PC,Percentage,1.376236,1995-01-01
1317,NaN,1313,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2000,PC,Percentage,1.380619,2000-01-01
1318,NaN,1314,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2001,PC,Percentage,1.380797,2001-01-01
1319,NaN,1315,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2002,PC,Percentage,1.381152,2002-01-01
1320,NaN,1316,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2003,PC,Percentage,1.381164,2003-01-01
1321,NaN,1317,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2004,PC,Percentage,1.381186,2004-01-01
1322,NaN,1318,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2005,PC,Percentage,1.381195,2005-01-01
1323,NaN,1319,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2006,PC,Percentage,18.871221,2006-01-01
1324,NaN,1320,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2007,PC,Percentage,18.871945,2007-01-01
1325,NaN,1321,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2008,PC,Percentage,18.872013,2008-01-01
1326,NaN,1322,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2009,PC,Percentage,18.872014,2009-01-01
1327,NaN,1323,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2010,PC,Percentage,19.015331,2010-01-01
1328,NaN,1324,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2011,PC,Percentage,19.016019,2011-01-01
1329,NaN,1325,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2012,PC,Percentage,19.025512,2012-01-01
1330,NaN,1326,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2013,PC,Percentage,19.081457,2013-01-01
1331,NaN,1327,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2014,PC,Percentage,19.081466,2014-01-01
1332,NaN,1328,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2015,PC,Percentage,19.082147,2015-01-01
1333,NaN,1329,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2016,PC,Percentage,19.110370,2016-01-01
1334,NaN,1330,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2017,PC,Percentage,19.110370,2017-01-01
1335,NaN,1331,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2018,PC,Percentage,19.110370,2018-01-01
1336,NaN,1332,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2019,PC,Percentage,19.110370,2019-01-01
1337,NaN,1333,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2020,PC,Percentage,19.110370,2020-01-01
1338,NaN,1334,USA,United States,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2021,PC,Percentage,19.110370,2021-01-01