In [2]:
import pandas as pd
import os
import seaborn as sns

In [6]:
os.chdir('c:\\Users\\Pablo\\Documents\\Climate DataThon 2022\\Climate-DataThon-2022\\Ocean Watch Data')

# Notes

Seems like for many countries the data was by decade for a while
We are going to need to filter some of these countries out possibly

In [8]:
marine_protection = pd.read_csv('Data\ocn_023_rw1_marine_protection_edit.csv')
marine_protection['datetime'] = pd.to_datetime(marine_protection['datetime'] )
marine_protection

,the_geom,cartodb_id,iso,country,designation,domain,measure,calculation_method,scope,year,unit_code,unit,value,datetime
0,NaN,1795,BRA,Brazil,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2018,PC,Percentage,26.650084,2018-01-01
1,NaN,4177,SAU,Saudi Arabia,"All, including data recorded as points",Marine,Square kilometers,Total for category,Country,1950,KM2,Square kilometres,6.570000,1950-01-01
2,NaN,5448,G20,G20,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2017,PC,Percentage,10.232679,2017-01-01
3,NaN,6536,URY,Uruguay,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2003,PC,Percentage,0.000717,2003-01-01
4,NaN,1,AUS,Australia,"All, including data recorded as points",Marine,Square kilometers,Total for category,Country,1950,KM2,Square kilometres,153.990000,1950-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6637,NaN,6637,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2017,PC,Percentage,9.851974,2017-01-01
6638,NaN,6638,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2018,PC,Percentage,10.907854,2018-01-01
6639,NaN,6639,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2019,PC,Percentage,11.002787,2019-01-01
6640,NaN,6640,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2020,PC,Percentage,11.002787,2020-01-01
6641,NaN,6641,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2021,PC,Percentage,11.002787,2021-01-01

### Get just the percentage, I imagine that's what we'd want

In [9]:
marine_protection_percent = marine_protection[marine_protection['unit_code'] == 'PC']
marine_protection_percent

,the_geom,cartodb_id,iso,country,designation,domain,measure,calculation_method,scope,year,unit_code,unit,value,datetime
0,NaN,1795,BRA,Brazil,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2018,PC,Percentage,26.650084,2018-01-01
2,NaN,5448,G20,G20,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2017,PC,Percentage,10.232679,2017-01-01
3,NaN,6536,URY,Uruguay,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2003,PC,Percentage,0.000717,2003-01-01
33,NaN,30,AUS,Australia,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,1950,PC,Percentage,0.002079,1950-01-01
34,NaN,31,AUS,Australia,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,1960,PC,Percentage,0.002081,1960-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6637,NaN,6637,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2017,PC,Percentage,9.851974,2017-01-01
6638,NaN,6638,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2018,PC,Percentage,10.907854,2018-01-01
6639,NaN,6639,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2019,PC,Percentage,11.002787,2019-01-01
6640,NaN,6640,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2020,PC,Percentage,11.002787,2020-01-01
6641,NaN,6641,EU27_2020,European Union Ã¢ÂÂ 27 countries (from 01/02...,"All, including data recorded as points",Marine,Percent of total land/EEZ area,Total for category,Country,2021,PC,Percentage,11.002787,2021-01-01

In [12]:
#marine_protection_percent[marine_protection_percent['country'] == 'United States']

### Convert to highcharts

In [27]:
code_dict = {'Faroe Islands': 'FO',
 'United States Minor Outlying Islands': 'UM',
 'United States': 'US',
 'Japan': 'JP',
 'Seychelles': 'SC',
 'India': 'IN',
 'France': 'FR',
 'Federated States of Micronesia': 'FM',
 "China (People's Republic of)" : 'CN',
 'China': 'CN',
 'Serranilla Bank': 'SW',
 'Scarborough Reef': 'SH',
 'Brazil': 'BR',
 'Ecuador': 'EC',
 'Australia': 'AU',
 'Kiribati': 'KI',
 'Philippines': 'PH',
 'Mexico': 'MX',
 'Spain': 'ES',
 'Bajo Nuevo Bank (Petrel Is.)': 'BU',
 'Maldives': 'MV',
 'Spratly Islands': 'SP',
 'United Kingdom': 'GB',
 'Greece': 'GR',
 'American Samoa': 'AS',
 'Denmark': 'DK',
 'Greenland': 'GL',
 'Guam': 'GU',
 'Northern Mariana Islands': 'MP',
 'Puerto Rico': 'PR',
 'United States Virgin Islands': 'VI',
 'Canada': 'CA',
 'Sao Tome and Principe': 'ST',
 'United Republic of Tanzania': 'TZ',
 'Cape Verde': 'CV',
 'Dominica': 'DM',
 'Netherlands': 'NL',
 'Jamaica': 'JM',
 'Samoa': 'WS',
 'Oman': 'OM',
 'Saint Vincent and the Grenadines': 'VC',
 'Turkey': 'TR',
 'Bangladesh': 'BD',
 'Solomon Islands': 'SB',
 'Saint Lucia': 'LC',
 'Nauru': 'NR',
 'Norway': 'NO',
 'Saint Kitts and Nevis': 'KN',
 'Bahrain': 'BH',
 'Tonga': 'TO',
 'Finland': 'FI',
 'Indonesia': 'ID',
 'Mauritius': 'MU',
 'Sweden': 'SE',
 'Trinidad and Tobago': 'TT',
 'Malaysia': 'MY',
 'The Bahamas': 'BS',
 'Panama': 'PA',
 'Palau': 'PW',
 'Tuvalu': 'TV',
 'Marshall Islands': 'MH',
 'Chile': 'CL',
 'Thailand': 'TH',
 'Grenada': 'GD',
 'Estonia': 'EE',
 'Antigua and Barbuda': 'AG',
 'Taiwan': 'TW',
 'Barbados': 'BB',
 'Italy': 'IT',
 'Malta': 'MT',
 'Papua New Guinea': 'PG',
 'Germany': 'DE',
 'Vanuatu': 'VU',
 'Singapore': 'SG',
 'Cyprus': 'CY',
 'Comoros': 'KM',
 'Fiji': 'FJ',
 'Russia': 'RU',
 'Russian Federation' :'RU',
 'Vatican': 'VA',
 'San Marino': 'SM',
 'Kazakhstan': 'KZ',
 'Azerbaijan': 'AZ',
 'Armenia': 'AM',
 'Tajikistan': 'TJ',
 'Lesotho': 'LS',
 'Uzbekistan': 'UZ',
 'Portugal': 'PT',
 'Morocco': 'MA',
 'Colombia': 'CO',
 'East Timor': 'TL',
 'Cambodia': 'KH',
 'Argentina': 'AR',
 'Saudi Arabia': 'SA',
 'Pakistan': 'PK',
 'Yemen': 'YE',
 'United Arab Emirates': 'AE',
 'Kenya': 'KE',
 'Peru': 'PE',
 'Dominican Republic': 'DO',
 'Haiti': 'HT',
 'Angola': 'AO',
 'Vietnam': 'VN',
 'Mozambique': 'MZ',
 'Costa Rica': 'CR',
 'Iran': 'IR',
 'El Salvador': 'SV',
 'Sierra Leone': 'SL',
 'Guinea Bissau': 'GW',
 'Croatia': 'HR',
 'Belize': 'BZ',
 'South Africa': 'ZA',
 'Democratic Republic of the Congo': 'CD',
 'Kuwait': 'KW',
 'Ireland': 'IE',
 'North Korea': 'KP',
 'South Korea': 'KR',
 'Guyana': 'GY',
 'Honduras': 'HN',
 'Myanmar': 'MM',
 'Gabon': 'GA',
 'Equatorial Guinea': 'GQ',
 'Nicaragua': 'NI',
 'Uganda': 'UG',
 'Malawi': 'MW',
 'Somaliland': 'SX',
 'Turkmenistan': 'TM',
 'Zambia': 'ZM',
 'Northern Cyprus': 'NC',
 'Mauritania': 'MR',
 'Algeria': 'DZ',
 'Lithuania': 'LT',
 'Ethiopia': 'ET',
 'Sudan': 'SD',
 'Eritrea': 'ER',
 'Ghana': 'GH',
 'Slovenia': 'SI',
 'Guatemala': 'GT',
 'Bosnia and Herzegovina': 'BA',
 'Jordan': 'JO',
 'Syria': 'SY',
 'Monaco': 'MC',
 'Albania': 'AL',
 'Uruguay': 'UY',
 'Cyprus No Mans Area': 'CN',
 'Mongolia': 'MN',
 'Rwanda': 'RW',
 'Somalia': 'SO',
 'Bolivia': 'BO',
 'Cameroon': 'CM',
 'Republic of Congo': 'CG',
 'Western Sahara': 'EH',
 'Republic of Serbia': 'RS',
 'Montenegro': 'ME',
 'Benin': 'BJ',
 'Nigeria': 'NG',
 'Togo': 'TG',
 'Laos': 'LA',
 'Afghanistan': 'AF',
 'Ukraine': 'UA',
 'Slovakia': 'SK',
 'Siachen Glacier': 'JK',
 'Bulgaria': 'BG',
 'Qatar': 'QA',
 'Liechtenstein': 'LI',
 'Austria': 'AT',
 'Swaziland': 'SZ',
 'Hungary': 'HU',
 'Romania': 'RO',
 'Luxembourg': 'LU',
 'Andorra': 'AD',
 'Ivory Coast': 'CI',
 'Liberia': 'LR',
 'Brunei': 'BN',
 'Belgium': 'BE',
 'Iraq': 'IQ',
 'Georgia': 'GE',
 'Gambia': 'GM',
 'Switzerland': 'CH',
 'Chad': 'TD',
 'Kosovo': 'KV',
 'Lebanon': 'LB',
 'Djibouti': 'DJ',
 'Burundi': 'BI',
 'Suriname': 'SR',
 'Israel': 'IL',
 'Mali': 'ML',
 'Senegal': 'SN',
 'Guinea': 'GN',
 'Zimbabwe': 'ZW',
 'Poland': 'PL',
 'Macedonia': 'MK',
 'Paraguay': 'PY',
 'Belarus': 'BY',
 'Latvia': 'LV',
 'Czech Republic': 'CZ',
 'Burkina Faso': 'BF',
 'Namibia': 'NA',
 'Niger': 'NE',
 'Libya': 'LY',
 'Tunisia': 'TN',
 'Bhutan': 'BT',
 'Moldova': 'MD',
 'South Sudan': 'SS',
 'Central African Republic': 'CF',
 'New Zealand': 'NZ',
 'Cuba': 'CU',
 'Venezuela': 'VE',
 'Madagascar': 'MG',
 'Iceland': 'IS',
 'Egypt': 'EG',
 'Sri Lanka': 'LK',
 'Botswana': 'BW',
 'Kyrgyzstan': 'KG',
 'Nepal': 'NP'}

In [33]:
marine_protection_percent_country = marine_protection_percent.groupby('country').mean().reset_index()
marine_protection_percent_country

,country,the_geom,cartodb_id,year,value
0,APEC,NaN,5264.0,2002.103448,5.647446
1,ASEAN,NaN,5206.0,2002.103448,1.249486
2,American Samoa,NaN,1494.0,2002.103448,7.185879
3,Anguilla,NaN,1552.0,2002.103448,0.063436
4,Areas beyond national jurisdiction,NaN,6366.0,2002.103448,0.150010
...,...,...,...,...,...
111,United States,NaN,1320.0,2002.103448,10.954389
112,United States Virgin Islands,NaN,4626.0,2002.103448,0.622153
113,Uruguay,NaN,6540.0,2002.103448,0.193295
114,Wallis and Futuna,NaN,4684.0,2002.103448,0.000000
115,World,NaN,4742.0,2002.103448,5.744182

In [34]:
marine_protection_percent_country['code'] = marine_protection_percent_country['country'].map(code_dict)
marine_protection_percent_country = marine_protection_percent_country.dropna(subset = ['code'])

In [30]:
highcharts_dict = []
for r, rows in marine_protection_percent_country.iterrows():
  highcharts_dict.append(
    {'code': rows.code, 
  'name' : rows.country,
   'value': rows.value
}
)

In [31]:
highcharts_dict

[{'code': 'AS', 'name': 'American Samoa', 'value': 7.185878671793103},
 {'code': 'AR', 'name': 'Argentina', 'value': 15.314965190965518},
 {'code': 'AU', 'name': 'Australia', 'value': 10.796568616275863},
 {'code': 'BE', 'name': 'Belgium', 'value': 16.234538473172414},
 {'code': 'BR', 'name': 'Brazil', 'value': 4.654000244172414},
 {'code': 'BG', 'name': 'Bulgaria', 'value': 3.505152331034483},
 {'code': 'CA', 'name': 'Canada', 'value': 1.5918167498275861},
 {'code': 'CL', 'name': 'Chile', 'value': 7.4177393705517245},
 {'code': 'CN',
  'name': "China (People's Republic of)",
  'value': 0.22316581344827588},
 {'code': 'CO', 'name': 'Colombia', 'value': 6.3477271465517235},
 {'code': 'CR', 'name': 'Costa Rica', 'value': 1.6215958448275862},
 {'code': 'HR', 'name': 'Croatia', 'value': 3.310364252655172},
 {'code': 'CY', 'name': 'Cyprus', 'value': 8.550322132275863},
 {'code': 'DK', 'name': 'Denmark', 'value': 12.632605311689655},
 {'code': 'DO', 'name': 'Dominican Republic', 'value': 7.4377013097241385},
 {'code': 'EC', 'name': 'Ecuador', 'value': 11.364154452068966},
 {'code': 'EE', 'name': 'Estonia', 'value': 11.917391169724137},
 {'code': 'FI', 'name': 'Finland', 'value': 8.738499436758621},
 {'code': 'FR', 'name': 'France', 'value': 29.48402310862069},
 {'code': 'GE', 'name': 'Georgia', 'value': 0.5057454986206897},
 {'code': 'DE', 'name': 'Germany', 'value': 30.641392245068964},
 {'code': 'GR', 'name': 'Greece', 'value': 3.906927372724138},
 {'code': 'GL', 'name': 'Greenland', 'value': 3.9577949871034486},
 {'code': 'GU', 'name': 'Guam', 'value': 10.667854467517243},
 {'code': 'IS', 'name': 'Iceland', 'value': 0.36097499037931036},
 {'code': 'IN', 'name': 'India', 'value': 0.04418274382758621},
 {'code': 'ID', 'name': 'Indonesia', 'value': 1.6850523953448278},
 {'code': 'IE', 'name': 'Ireland', 'value': 1.1544893551034483},
 {'code': 'IL', 'name': 'Israel', 'value': 0.046202369586206896},
 {'code': 'IT', 'name': 'Italy', 'value': 4.112836718241379},
 {'code': 'JP', 'name': 'Japan', 'value': 7.493847895379311},
 {'code': 'LV', 'name': 'Latvia', 'value': 7.980221890482759},
 {'code': 'LT', 'name': 'Lithuania', 'value': 17.495391748965517},
 {'code': 'MT', 'name': 'Malta', 'value': 4.131193707344828},
 {'code': 'MX', 'name': 'Mexico', 'value': 5.359426632206897},
 {'code': 'NL', 'name': 'Netherlands', 'value': 15.14277658962069},
 {'code': 'NZ', 'name': 'New Zealand', 'value': 15.993242247},
 {'code': 'MP',
  'name': 'Northern Mariana Islands',
  'value': 12.047654060034484},
 {'code': 'NO', 'name': 'Norway', 'value': 0.5137672402758621},
 {'code': 'PE', 'name': 'Peru', 'value': 0.3186800905862069},
 {'code': 'PL', 'name': 'Poland', 'value': 15.347085723758621},
 {'code': 'PT', 'name': 'Portugal', 'value': 2.860783329896552},
 {'code': 'PR', 'name': 'Puerto Rico', 'value': 1.5667809725172415},
 {'code': 'RO', 'name': 'Romania', 'value': 8.498946980965517},
 {'code': 'RU', 'name': 'Russia', 'value': 0.8259642332413792},
 {'code': 'SA', 'name': 'Saudi Arabia', 'value': 2.164043509},
 {'code': 'SI', 'name': 'Slovenia', 'value': 2.0524468304827588},
 {'code': 'ZA', 'name': 'South Africa', 'value': 3.9747823343448276},
 {'code': 'ES', 'name': 'Spain', 'value': 6.526795010758621},
 {'code': 'SE', 'name': 'Sweden', 'value': 6.602887406724138},
 {'code': 'UA', 'name': 'Ukraine', 'value': 2.817178711724138},
 {'code': 'GB', 'name': 'United Kingdom', 'value': 10.289299546689655},
 {'code': 'US', 'name': 'United States', 'value': 10.954388742068964},
 {'code': 'VI',
  'name': 'United States Virgin Islands',
  'value': 0.6221527951034482},
 {'code': 'UY', 'name': 'Uruguay', 'value': 0.19329488665517242}]